### ISSUE TITLE
[전체]View 구성(D:3,P:30)

### ISSUE THREAD

**Issue by kobowon** [kobowon/Together-Admin#3]
Bootstrap 템플릿 구매후 프로젝트에 결합 후, 서버 동작시 뷰가 보이면 종료

**Comment by soyoung6488** [comment]
1일차 express에서 HTML 파일올렸더니 경로 제대로 넣었지만 찾지못해 에러.....
![image](https://user-images.githubusercontent.com/22609946/39426681-c7345864-4cbb-11e8-95ff-4ae58278a94d.png)

**Comment by soyoung6488** [comment]
해결함, 기본 화면(index.html) 그대로 나오는 것 확인 함.
